replicaCount: 2

image:
  repository: thecloudguyn/redditclone
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

containerPort: 3000

labels:
  app: redditclone-service 
